/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as MyGiftsRouteImport } from './routes/my-gifts'
import { Route as ListaDePresentesRouteImport } from './routes/lista-de-presentes'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListaDePresentesIndexRouteImport } from './routes/lista-de-presentes.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ListaDePresentesOccasionRouteImport } from './routes/lista-de-presentes.$occasion'
import { Route as EventsCreateRouteImport } from './routes/events.create'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EventsSlugConviteParceiroRouteImport } from './routes/events.$slug_.convite-parceiro'
import { Route as ApiSlopRevalidateRouteImport } from './routes/api.slop.revalidate'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGiftsRoute = MyGiftsRouteImport.update({
  id: '/my-gifts',
  path: '/my-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaDePresentesRoute = ListaDePresentesRouteImport.update({
  id: '/lista-de-presentes',
  path: '/lista-de-presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaDePresentesIndexRoute = ListaDePresentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListaDePresentesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaDePresentesOccasionRoute =
  ListaDePresentesOccasionRouteImport.update({
    id: '/$occasion',
    path: '/$occasion',
    getParentRoute: () => ListaDePresentesRoute,
  } as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EventsSlugConviteParceiroRoute =
  EventsSlugConviteParceiroRouteImport.update({
    id: '/events/$slug_/convite-parceiro',
    path: '/events/$slug/convite-parceiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSlopRevalidateRoute = ApiSlopRevalidateRouteImport.update({
  id: '/api/slop/revalidate',
  path: '/api/slop/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lista-de-presentes': typeof ListaDePresentesRouteWithChildren
  '/my-gifts': typeof MyGiftsRoute
  '/precos': typeof PrecosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/lista-de-presentes/$occasion': typeof ListaDePresentesOccasionRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/lista-de-presentes/': typeof ListaDePresentesIndexRoute
  '/api/slop/revalidate': typeof ApiSlopRevalidateRoute
  '/events/$slug/convite-parceiro': typeof EventsSlugConviteParceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-gifts': typeof MyGiftsRoute
  '/precos': typeof PrecosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/lista-de-presentes/$occasion': typeof ListaDePresentesOccasionRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
  '/lista-de-presentes': typeof ListaDePresentesIndexRoute
  '/api/slop/revalidate': typeof ApiSlopRevalidateRoute
  '/events/$slug/convite-parceiro': typeof EventsSlugConviteParceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lista-de-presentes': typeof ListaDePresentesRouteWithChildren
  '/my-gifts': typeof MyGiftsRoute
  '/precos': typeof PrecosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/lista-de-presentes/$occasion': typeof ListaDePresentesOccasionRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/lista-de-presentes/': typeof ListaDePresentesIndexRoute
  '/api/slop/revalidate': typeof ApiSlopRevalidateRoute
  '/events/$slug_/convite-parceiro': typeof EventsSlugConviteParceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/faq'
    | '/how-it-works'
    | '/lista-de-presentes'
    | '/my-gifts'
    | '/precos'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/demo/convex'
    | '/demo/posthog'
    | '/events/$slug'
    | '/events/create'
    | '/lista-de-presentes/$occasion'
    | '/sitemap/xml'
    | '/blog/'
    | '/lista-de-presentes/'
    | '/api/slop/revalidate'
    | '/events/$slug/convite-parceiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/how-it-works'
    | '/my-gifts'
    | '/precos'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/demo/convex'
    | '/demo/posthog'
    | '/events/$slug'
    | '/events/create'
    | '/lista-de-presentes/$occasion'
    | '/sitemap/xml'
    | '/blog'
    | '/lista-de-presentes'
    | '/api/slop/revalidate'
    | '/events/$slug/convite-parceiro'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/faq'
    | '/how-it-works'
    | '/lista-de-presentes'
    | '/my-gifts'
    | '/precos'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/demo/convex'
    | '/demo/posthog'
    | '/events/$slug'
    | '/events/create'
    | '/lista-de-presentes/$occasion'
    | '/sitemap/xml'
    | '/blog/'
    | '/lista-de-presentes/'
    | '/api/slop/revalidate'
    | '/events/$slug_/convite-parceiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListaDePresentesRoute: typeof ListaDePresentesRouteWithChildren
  MyGiftsRoute: typeof MyGiftsRoute
  PrecosRoute: typeof PrecosRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsCreateRoute: typeof EventsCreateRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiSlopRevalidateRoute: typeof ApiSlopRevalidateRoute
  EventsSlugConviteParceiroRoute: typeof EventsSlugConviteParceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-gifts': {
      id: '/my-gifts'
      path: '/my-gifts'
      fullPath: '/my-gifts'
      preLoaderRoute: typeof MyGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-de-presentes': {
      id: '/lista-de-presentes'
      path: '/lista-de-presentes'
      fullPath: '/lista-de-presentes'
      preLoaderRoute: typeof ListaDePresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-de-presentes/': {
      id: '/lista-de-presentes/'
      path: '/'
      fullPath: '/lista-de-presentes/'
      preLoaderRoute: typeof ListaDePresentesIndexRouteImport
      parentRoute: typeof ListaDePresentesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-de-presentes/$occasion': {
      id: '/lista-de-presentes/$occasion'
      path: '/$occasion'
      fullPath: '/lista-de-presentes/$occasion'
      preLoaderRoute: typeof ListaDePresentesOccasionRouteImport
      parentRoute: typeof ListaDePresentesRoute
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/events/$slug_/convite-parceiro': {
      id: '/events/$slug_/convite-parceiro'
      path: '/events/$slug/convite-parceiro'
      fullPath: '/events/$slug/convite-parceiro'
      preLoaderRoute: typeof EventsSlugConviteParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slop/revalidate': {
      id: '/api/slop/revalidate'
      path: '/api/slop/revalidate'
      fullPath: '/api/slop/revalidate'
      preLoaderRoute: typeof ApiSlopRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ListaDePresentesRouteChildren {
  ListaDePresentesOccasionRoute: typeof ListaDePresentesOccasionRoute
  ListaDePresentesIndexRoute: typeof ListaDePresentesIndexRoute
}

const ListaDePresentesRouteChildren: ListaDePresentesRouteChildren = {
  ListaDePresentesOccasionRoute: ListaDePresentesOccasionRoute,
  ListaDePresentesIndexRoute: ListaDePresentesIndexRoute,
}

const ListaDePresentesRouteWithChildren =
  ListaDePresentesRoute._addFileChildren(ListaDePresentesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListaDePresentesRoute: ListaDePresentesRouteWithChildren,
  MyGiftsRoute: MyGiftsRoute,
  PrecosRoute: PrecosRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsCreateRoute: EventsCreateRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiSlopRevalidateRoute: ApiSlopRevalidateRoute,
  EventsSlugConviteParceiroRoute: EventsSlugConviteParceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
